name: Repo Settings

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  administration: write

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Apply repository description and topics
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/')
            // 1) Description courte
            await github.request('PATCH /repos/{owner}/{repo}', {
              owner,
              repo,
              description: 'Seeker — orchestrateur multi‑stratégies d’options risk‑defined avec agents (Risk, Liquidité, Événements, FX), exécution IBKR (paper), API + UI dark, Docker.'
            })
            // 2) Topics
            await github.request('PUT /repos/{owner}/{repo}/topics', {
              owner,
              repo,
              names: [
                'options-trading',
                'ibkr',
                'bandit',
                'fastapi',
                'docker',
                'reinforcement-learning',
                'trading-bot'
              ]
            })
      - name: Protect main branch
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/')
            // Protection minimale robuste: PR review requise, pas de force-push ni suppression, linéaire
            await github.request('PUT /repos/{owner}/{repo}/branches/{branch}/protection', {
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['CI / test']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              required_linear_history: true,
              lock_branch: false,
              required_conversation_resolution: true
            })


